### ISSUE TITLE
Project generation hangs on Windows/WSL with latest release

### ISSUE THREAD

**Issue by ivoencarnacao** [wimdeblauwe/ttcli#181] opened 2024-12-01 22:47 UTC
I have been trying to run ttcli during the weekend to follow Taming Thymeleaf but I have not been sucessful.

With Spring Boot 3.4, npm and Tailwind it hangs on updating Maven pom.xml.
![win_npm](https://github.com/user-attachments/assets/cef32781-62f3-4742-afb7-8fafd0836f10)
[win_npm_ttcli.log](https://github.com/user-attachments/files/17970549/win_npm_ttcli.log)

With Spring Boot 3.4, Vite and Tailwind it hangs on adding npm build scripts.
![win_vite](https://github.com/user-attachments/assets/ee403305-8fe4-485d-8dfc-d8dd876747e2)
[win_vite_ttcli.log](https://github.com/user-attachments/files/17970566/win_vite_ttcli.log)

Is there something else I could provide or do to help debug this situation?

These screenshots/logs were taken running `java -jar ttcli-1.5.2.jar init` on a Windows 10 box with Java 23 and Node LTS 22.11.

Thanks in advance,
Ivo.

**Comment by wimdeblauwe** [comment] 2024-12-02 07:41
Duplicate of #172 I think.

**Comment by ivoencarnacao** [comment] 2024-12-02 16:51
Any plans on fixing these?
I can provide more info for debugging if needed.

**Comment by wimdeblauwe** [comment] 2024-12-03 17:04
I would love to fix it if I would know how. I unfortunately don't have a Windows machine.

**Comment by wimdeblauwe** [comment] 2024-12-03 17:08
I see in the log file you have provided that it seems to hang trying to format the `pom.xml` file using `mvn au.com.acegi:xml-format-maven-plugin:4.0.1:xml-format -DindentSize=4`. Can you try to run this command manually to see what happens if you do?

**Comment by wimdeblauwe** [comment] 2024-12-03 17:19
Even better. Can you add this line in the `MavenPomReaderWriter.java` file?

```
builder.redirectOutput(ProcessBuilder.Redirect.appendTo(new File("mvn-output.txt")));
```

It should be added just after this line:
```
builder.redirectError(ProcessBuilder.Redirect.INHERIT);
```

Then run `mvn verify` and run `java -jar target/ttcli-1.6.0-SNAPSHOT.jar init`. There should now be a `mvn-output.txt` file generated in the project. If you could send me the output, that might help debug the issue.

**Comment by ivoencarnacao** [comment] 2024-12-03 18:53
> Even better. Can you add this line in the `MavenPomReaderWriter.java` file?
> 
> ```
> builder.redirectOutput(ProcessBuilder.Redirect.appendTo(new File("mvn-output.txt")));
> ```
> 
> It should be added just after this line:
> 
> ```
> builder.redirectError(ProcessBuilder.Redirect.INHERIT);
> ```
> 
> Then run `mvn verify` and run `java -jar target/ttcli-1.6.0-SNAPSHOT.jar init`. There should now be a `mvn-output.txt` file generated in the project. If you could send me the output, that might help debug the issue.


I'm glad to help in anyway I can!

These are the defaults I used:
![ttcli_sb4_npm](https://github.com/user-attachments/assets/7dc5bc33-2ba1-4186-b785-48253c641418)

And this is the `mvn-output.txt` file you requested:
[mvn-output.txt](https://github.com/user-attachments/files/17997600/mvn-output.txt)

Thank you for your attention and availability!

**Comment by ivoencarnacao** [comment] 2024-12-03 19:02
> I see in the log file you have provided that it seems to hang trying to format the `pom.xml` file using `mvn au.com.acegi:xml-format-maven-plugin:4.0.1:xml-format -DindentSize=4`. Can you try to run this command manually to see what happens if you do?

This is the ouput I get:

```bash
mvn au.com.acegi:xml-format-maven-plugin:4.0.1:xml-format -DindentSize=4
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------       
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------       
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.bitness: 64
[INFO] os.detected.version: 10.0
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 0
[INFO] os.detected.classifier: windows-x86_64
[INFO]
[INFO] --------------------< io.github.wimdeblauwe:ttcli >---------------------       
[INFO] Building Taming Thymeleaf CLI 1.6.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------       
[INFO]
[INFO] --- xml-format-maven-plugin:4.0.1:xml-format (default-cli) @ ttcli ---
[INFO] ------------------------------------------------------------------------       
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------       
[INFO] Total time:  1.780 s
[INFO] Finished at: 2024-12-03T18:57:40Z
[INFO] ------------------------------------------------------------------------ 
```

**Comment by wimdeblauwe** [comment] 2024-12-03 20:11
Did it now create the project without problems? Or did it still hang?

**Comment by ivoencarnacao** [comment] 2024-12-03 20:19
> Did it now create the project without problems? Or did it still hang?

It created the project without problems using Spring Boot 3.4 and npm.

**Comment by wimdeblauwe** [comment] 2024-12-03 21:19
Very interesting. I'll create a new version using that info.

**Closed** 2024-12-03 22:01 UTC

**Comment by wimdeblauwe** [comment] 2024-12-03 22:59
1.6.1 is now released with a fix for this, please test it! See https://github.com/wimdeblauwe/ttcli/releases/tag/1.6.1 (and https://github.com/wimdeblauwe/ttcli/releases/tag/1.6.0)

**Comment by ivoencarnacao** [comment] 2024-12-04 00:49
> 1.6.1 is now released with a fix for this, please test it! See https://github.com/wimdeblauwe/ttcli/releases/tag/1.6.1 (and https://github.com/wimdeblauwe/ttcli/releases/tag/1.6.0)

1.6.1 with Spring Boot 3.4 and npm or Vite, are both working fine so far, the project finishes generating the files and the application starts without problems.

I will give better feedback in the following days, as I get back to your book!

Once again, 
Thank You for your attention and availability!
