### ISSUE TITLE
ttcli doest not complete the project generation

### ISSUE THREAD

**Issue by Paulo1661** [wimdeblauwe/ttcli#172] opened 2024-10-26 15:13 UTC
Windows : The process does not exit and the project is not completely generated (tailwind css not configure). 

![{F93D6DE4-6816-4B0E-AF4A-6EA9B32330F2}](https://github.com/user-attachments/assets/99495dbb-8977-49a7-8cd0-f75c0b756bda)

[ttcli.log](https://github.com/user-attachments/files/17530822/ttcli.log)

Mac Os: The process ends with and error : unable to init tailwind. but looks like the tailwind was correctly configure

**Comment by wimdeblauwe** [comment] 2024-10-28 06:37
The log file shows: `java.nio.charset.UnsupportedCharsetException: Cp1252`. I wonder if this could be due to the native compilation with GraalVM. Can you try downloading the jar file from https://github.com/wimdeblauwe/ttcli/releases/tag/1.5.1 and run it with `java -jar ttcli-1.5.1.jar init` ? Note that It is compiled against Java 23.

**Comment by adigiurgi** [comment] 2024-11-17 08:22
I had the same problem on windows. I tried to run it with java also but with no positive effect. At some point (when installing babel - see print screen) it would just freeze.
![ttcli-bug](https://github.com/user-attachments/assets/672e585c-c0f0-4050-9cfa-8d9927200b77)

I switched to the previous version release (1.4.2) and it was all good.

**Comment by wimdeblauwe** [comment] 2024-11-17 10:00
It is unfortunate I don't have Windows to test what is going on. As an alternative, you could try the Vite option to see if that works instead of the npm option?

**Comment by adigiurgi** [comment] 2024-11-17 16:12
I tried the Vite option and it still freezes. Also with the Devtools option. Something is of on Windows with the latest release. It works with 1.4.2 though which is fine for me.

**Comment by wimdeblauwe** [comment] 2024-12-03 22:19
Should be fixed once 1.6.0 is released as I think it is a duplicate of #183

**Closed by wimdeblauwe** 2024-12-03 22:19 UTC

**Comment by wimdeblauwe** [comment] 2024-12-03 22:59
1.6.1 is now released with a fix for this, please test it! See https://github.com/wimdeblauwe/ttcli/releases/tag/1.6.1 (and https://github.com/wimdeblauwe/ttcli/releases/tag/1.6.0)
